# -*- coding: utf-8 -*-
"""Untitled4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117Mq6nb3toHTxnAxbPvjOUa_PXPyaWUa
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import pandas as pd
# import streamlit as st
# import seaborn as sns
# import matplotlib.pyplot as plt
# st.set_page_config(page_title ='Student dashboard',layout='wide')
# st.title('🎓 Student Marks Analysis Dashboard')
# df=pd.read_csv('StudentsPerformance.csv')
# st.sidebar.header('🔍 Filter Students')
# student=st.sidebar.multiselect('Selecting Students',options=df['Name'].unique(),default=df['Name'].unique())
# filtered_df=df[(df['Name'].isin(student))]
# avg_total = filtered_df[["Maths","Science","English","Computer"]].mean().mean()
# topper = filtered_df.set_index("Name")[["Maths","Science","English","Computer"]].sum(axis=1).idxmax()
# 
# col1, col2 = st.columns(2)
# col1.metric("📊 Overall Average Marks", f"{avg_total:.1f}")
# col2.metric("🏆 Top Performer", topper)
# st.subheader("📊 Average Marks per Subject")
# 
# avg_marks = filtered_df[["Maths","Science","English","Computer"]].mean()
# 
# fig1, ax1 = plt.subplots()
# sns.barplot(x=avg_marks.index, y=avg_marks.values, ax=ax1)
# ax1.set_xlabel("Subject")
# ax1.set_ylabel("Average Marks")
# st.pyplot(fig1)
# 
# 
# st.subheader("📦 Subject-wise Marks Distribution")
# 
# fig2, ax2 = plt.subplots()
# sns.boxplot(data=filtered_df[["Maths","Science","English","Computer"]], ax=ax2)
# ax2.set_ylabel("Marks")
# st.pyplot(fig2)
# 
# 
# st.subheader("🔥 Subject Correlation Heatmap")
# 
# corr = filtered_df[["Maths","Science","English","Computer"]].corr()
# 
# fig3, ax3 = plt.subplots()
# sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax3)
# st.pyplot(fig3)
# 
# 
# st.subheader("📄 Student Marks Data")
# st.dataframe(filtered_df)
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile StudentsPerformance.csv
# Name,Maths,Science,English,Computer
# Aman,78,85,74,90
# Riya,88,92,81,95
# Karan,65,70,68,72
# Sneha,90,94,89,96
# Rahul,55,60,58,62
# Neha,82,88,80,91
# Arjun,70,75,72,78
# Pooja,92,95,90,98
#

from pyngrok import ngrok
ngrok.set_auth_token("38YaBUs68FAXQFusXLyBDxk8SYo_2dazQfqgzgkREwA3MVrKo")

!pip install streamlit pyngrok

from pyngrok import ngrok
ngrok.kill()

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

public_url = ngrok.connect(8501)
public_url

